In [95]:
import os
import numpy as np
import matplotlib
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd





mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)
# to make this notebook's output stable across runs


crash= pd.read_csv("New_Virginia_Crashes.csv")
crash


years = crash["Fatal_Crashes"].groupby(crash['Crash_Year'])
print(years.value_counts())
years.sum()





# crash.info()
# crash.describe()

### 1(a) File size: 0.15 MB
### 1(b) 1599 entries
### 1(c) 11 features and 1 label(quality)
### 1(d) You can find the mean, standard deviation, minimum, maximum, 25% 50% 75% percentiles for each of the features and the label. 
# crash.hist(bins=50, figsize=(20,20))

# plt.show()


Crash_Year  Fatal_Crashes
2013        0                1617
            1                   5
2014        0                1584
            1                   6
2015        0                1739
            1                  16
2016        0                1707
            1                  11
2017        0                1731
            1                  13
2018        0                1604
            1                   6
Name: Fatal_Crashes, dtype: int64


Crash_Year
2013     5
2014     6
2015    16
2016    11
2017    13
2018     6
Name: Fatal_Crashes, dtype: int64

In [96]:
pd.DataFrame(crash)

severity = crash['Crash_Severity']  
print(len(severity))
severity

new = []  #new array to append values to 

for i in crash['Crash_Severity']:  
    if i == "B":  
        new.append(1)
    elif i == "A": 
        new.append(1)
    elif i == "K": 
        new.append(1)
    elif i == "C": 
        new.append(1)
    else:
        new.append(0)

print(len(new))
crash['injury'] = new   #adds a column to the dataframe
crash['injury']
crash


10039
10039


X          Y  OBJECTID  A_Crash  A_People  B_Crash  B_People  \
0     -79.060083  37.392427      1001        0         0        0         0   
1     -76.159622  36.837317      1002        0         0        1         4   
2     -77.387503  38.982145      1003        0         0        1         1   
3     -77.757742  37.692898      1004        0         0        0         0   
4     -76.194992  36.814577      1005        0         0        0         0   
5     -77.132992  38.796868      1006        0         0        0         0   
6     -76.410552  37.124597      1007        0         0        0         0   
7     -77.389012  37.543678      1008        1         1        0         2   
8     -78.834343  38.342838      1009        0         0        0         0   
9     -78.154253  39.176398      1010        0         0        0         0   
10    -76.089192  36.868707      1011        0         0        0         0   
11    -79.827244  37.824417      1012        0         0        0         0   
12    -77.309432  38.868868      1013        0         0        1         1   
13    -76.363042  36.820187      1014        0         0        0         0   
14    -77.061110  38.827508      1015        0         0        0         0   
15    -76.412414  36.997280      1016        0         0        0         0   
16    -78.214073  39.081258      1017        0         0        0         0   
17    -76.206882  36.754497      1018        0         0        0         0   
18    -77.099272  38.884748      1019        0         0        1         1   
19    -76.503742  37.105977      1020        0         0        0         0   
20    -78.497673  38.057608      1021        0         0        0         0   
21    -78.359308  37.742612      1022        0         0        0         0   
22    -78.490933  38.063008      1023        0         0        0         0   
23    -77.520832  37.613288      1024        0         0        1         1   
24    -79.981793  37.294437      1025        0         0        0         0   
25    -82.017887  36.691285      1026        0         0        0         0   
26    -76.195452  36.864297      1027        0         0        0         0   
27    -77.182732  38.765308      1028        0         0        0         0   
28    -77.434816  38.616509      1029        0         0        1         1   
29    -78.947428  36.675727      1030        0         0        0         0   
...          ...        ...       ...      ...       ...      ...       ...   
10009 -81.817056  37.094039     14010        0         0        0         0   
10010 -77.606952  37.511897     14011        0         0        0         0   
10011 -76.184142  36.844847     14012        0         0        1         1   
10012 -80.010883  37.209417     14013        0         0        0         0   
10013 -77.562182  37.662868     14014        0         0        1         1   
10014 -77.457062  38.297768     14015        0         0        0         0   
10015 -76.582302  36.714867     14016        0         0        1         1   
10016 -81.089953  36.955227     14017        0         0        0         0   
10017 -77.099142  38.834158     14018        0         0        0         0   
10018 -77.900653  38.875578     14019        0         0        0         0   
10019 -77.088272  38.838318     14020        0         0        0         0   
10020 -76.731665  37.254109     14021        0         0        0         0   
10021 -77.083302  38.742668     14022        0         0        0         0   
10022 -77.450522  38.749208     14023        0         0        0         0   
10023 -78.251123  39.201248     14024        0         0        0         0   
10024 -76.086142  36.799757     14025        0         0        1         1   
10025 -78.183313  37.190087     14026        1         1        0         1   
10026 -77.301312  38.826388     14027        0         0        0         0   
10027 -77.320712  37.587818     14028        0         0        0

In [98]:
# You might want to use the following package
from sklearn.model_selection import train_test_split
from pandas.plotting import scatter_matrix # optional
from sklearn.preprocessing import Imputer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# Your code goes here for this section.
np.random.seed(42)
crash2 = crash.drop(['OBJECTID', 'A_Crash','A_People','B_Crash','Driverinjurytype','B_People','X', 'Y', 'Crash_Dsc', 'Crash_Dt','Crash_Military_Tm','C_Crash','C_People','Crash_Severity','District_C', 'Fatal_Crashes', 'Document_Nbr', 'Pedestrians_Killed','Juris_Code', 'Vehicle_Body_Type_Cd', 'Juris_Name', 'Local_Case_Cd','Mpo_Name','Passage','Passgen','Pedgen','Passinjurytype','Pdo_Crash','Rns_Mp','Pedage','Pedinjurytype','Rte_Nm','Vehiclenumber','Vsp_1'], axis=1)

y= crash2.injury

print(sum(y))
# X= crash.drop('injury', axis=1)

X= crash2.drop('injury', axis=1)





X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=int(len(crash)*.20))
print(X_train.head())
print(len(X_train))
print(len(X_test))
print(len(y_test))


crash2


3462
                  Collision_Type  Crash_Year Driverage           Drivergen  \
5856  9. Fixed Object - Off Road        2014        20              Female   
6692                 1. Rear End        2014     24,26       Female,Female   
5572                 1. Rear End        2013  20,20,43  Female,Female,Male   
1392  9. Fixed Object - Off Road        2015        19                Male   
1921                 1. Rear End        2018     19,29           Male,Male   

                                  Driver_Action_Type_Cd  Gps_Latitude_Nbr  \
5856                40. Fail to Maintain Proper Control        -77.007220   
6692      12. Following Too Close,1. No Improper Action        -79.966310   
5572  12. Following Too Close,1. No Improper Action,...        -77.318743   
1392                40. Fail to Maintain Proper Control        -78.648030   
1921      12. Following Too Close,1. No Improper Action        -77.356330   

      Gps_Longitude_Nbr                 Light_Condition  \
5856

Collision_Type  Crash_Year    Driverage  \
0                            1. Rear End        2016        18,19   
1                               2. Angle        2017     32,51,33   
2             9. Fixed Object - Off Road        2013           16   
3             9. Fixed Object - Off Road        2017           49   
4                            1. Rear End        2014        18,21   
5                            1. Rear End        2017     17,55,66   
6                            1. Rear End        2014     21,67,63   
7                               2. Angle        2015        52,76   
8                               10. Deer        2017           39   
9             9. Fixed Object - Off Road        2018           21   
10            9. Fixed Object - Off Road        2018          NaN   
11                              2. Angle        2013           36   
12                           1. Rear End        2015        34,63   
13                            3. Head On        2016           17   
14                              2. Angle        2013        55,19   
15         4. Sideswipe - Same Direction        2013        31,23   
16                           1. Rear End        2014        26,22   
17                              2. Angle        2015        57,67   
18                              2. Angle        2016           42   
19                           1. Rear End        2017        19,52   
20                              2. Angle        2018     42,26,42   
21                             16. Other        2013           24   
22                           1. Rear End        2015        25,67   
23                               12. Ped        2017          NaN   
24                           1. Rear End        2017        35,26   
25                              2. Angle        2013        38,24   
26                           1. Rear End        2015     19,24,69   
27                           1. Rear End        2017        23,46   
28            9. Fixed Object - Off Road        2013           54   
29                              10. Deer        2013           43   
...                                  ...         ...          ...   
10009                        1. Rear End        2013     41,65,63   
10010                           2. Angle        2014        58,66   
10011                        1. Rear End        2014     34,79,60   
10012                         3. Head On        2017     32,57,69   
10013      4. Sideswipe - Same Direction        2017        47,39   
10014         9. Fixed Object - Off Road        2018           18   
10015                          16. Other        2018           39   
10016  5. Sideswipe - Opposite Direction        2018        63,39   
10017                        1. Rear End        2015        21,33   
10018                        1. Rear End        2015        50,24   
10019                        1. Rear End        2017        34,61   
10020                        1. Rear End        2013        48,69   
10021                        1. Rear End        2014  46,63,34,28   
10022                           2. Angle        2014        69,31   
10023                           2. Angle        2015        60,44   
10024                        1. Rear End        2016     24,57,37   
10025                           2. Angle        2017        64,22   
10026                        1. Rear End        2017  62,38,28,41   
10027         9. Fixed Object - Off Road        2016           19   
10028      4. Sideswipe - Same Direction        2015        32,24   
10029                        1. Rear End        2018     58,47,25   
10030                           2. Angle        2013        18,53   
10031                           2. Angle        2014           22   
10032                        1. Rear End        2017        17,66   
10033  5. Sideswipe - Opposite Direction        2017           29   
10034                           2. Angle        2013        47,44   
10035         9. Fixed O

In [99]:
np.sum(crash2.isnull()) ## We have no null values


Collision_Type             0
Crash_Year                 0
Driverage                183
Drivergen                  0
Driver_Action_Type_Cd      0
Gps_Latitude_Nbr           6
Gps_Longitude_Nbr          6
Light_Condition            0
Plan_Dist_Name             0
Roadway_Surface_Cond       0
Weather_Condition          0
injury                     0
dtype: int64

In [100]:
#crash2[crash2['Pedestrians_Killed']==1]

In [101]:
crash2

Collision_Type  Crash_Year    Driverage  \
0                            1. Rear End        2016        18,19   
1                               2. Angle        2017     32,51,33   
2             9. Fixed Object - Off Road        2013           16   
3             9. Fixed Object - Off Road        2017           49   
4                            1. Rear End        2014        18,21   
5                            1. Rear End        2017     17,55,66   
6                            1. Rear End        2014     21,67,63   
7                               2. Angle        2015        52,76   
8                               10. Deer        2017           39   
9             9. Fixed Object - Off Road        2018           21   
10            9. Fixed Object - Off Road        2018          NaN   
11                              2. Angle        2013           36   
12                           1. Rear End        2015        34,63   
13                            3. Head On        2016           17   
14                              2. Angle        2013        55,19   
15         4. Sideswipe - Same Direction        2013        31,23   
16                           1. Rear End        2014        26,22   
17                              2. Angle        2015        57,67   
18                              2. Angle        2016           42   
19                           1. Rear End        2017        19,52   
20                              2. Angle        2018     42,26,42   
21                             16. Other        2013           24   
22                           1. Rear End        2015        25,67   
23                               12. Ped        2017          NaN   
24                           1. Rear End        2017        35,26   
25                              2. Angle        2013        38,24   
26                           1. Rear End        2015     19,24,69   
27                           1. Rear End        2017        23,46   
28            9. Fixed Object - Off Road        2013           54   
29                              10. Deer        2013           43   
...                                  ...         ...          ...   
10009                        1. Rear End        2013     41,65,63   
10010                           2. Angle        2014        58,66   
10011                        1. Rear End        2014     34,79,60   
10012                         3. Head On        2017     32,57,69   
10013      4. Sideswipe - Same Direction        2017        47,39   
10014         9. Fixed Object - Off Road        2018           18   
10015                          16. Other        2018           39   
10016  5. Sideswipe - Opposite Direction        2018        63,39   
10017                        1. Rear End        2015        21,33   
10018                        1. Rear End        2015        50,24   
10019                        1. Rear End        2017        34,61   
10020                        1. Rear End        2013        48,69   
10021                        1. Rear End        2014  46,63,34,28   
10022                           2. Angle        2014        69,31   
10023                           2. Angle        2015        60,44   
10024                        1. Rear End        2016     24,57,37   
10025                           2. Angle        2017        64,22   
10026                        1. Rear End        2017  62,38,28,41   
10027         9. Fixed Object - Off Road        2016           19   
10028      4. Sideswipe - Same Direction        2015        32,24   
10029                        1. Rear End        2018     58,47,25   
10030                           2. Angle        2013        18,53   
10031                           2. Angle        2014           22   
10032                        1. Rear End        2017        17,66   
10033  5. Sideswipe - Opposite Direction        2017           29   
10034                           2. Angle        2013        47,44   
10035         9. Fixed O

In [119]:
# smoke_num = insurance.drop('smoker', axis=1)
# region_num = smoke_num.drop('region', axis=1)
# sex_num = region_num.drop('sex', axis=1)

coll_type = crash2.drop('Collision_Type', axis=1)
light_con = coll_type.drop('Light_Condition', axis=1)
roadway = light_con.drop('Roadway_Surface_Cond', axis=1)
weather = roadway.drop('Weather_Condition', axis=1)


coll_cat = crash2[['Collision_Type']]
light_cat = crash2[['Light_Condition']]
roadway_cat = crash2[['Roadway_Surface_Cond']]
weather_cat = crash2[['Weather_Condition']]

print(coll_cat)






                          Collision_Type
0                            1. Rear End
1                               2. Angle
2             9. Fixed Object - Off Road
3             9. Fixed Object - Off Road
4                            1. Rear End
5                            1. Rear End
6                            1. Rear End
7                               2. Angle
8                               10. Deer
9             9. Fixed Object - Off Road
10            9. Fixed Object - Off Road
11                              2. Angle
12                           1. Rear End
13                            3. Head On
14                              2. Angle
15         4. Sideswipe - Same Direction
16                           1. Rear End
17                              2. Angle
18                              2. Angle
19                           1. Rear End
20                              2. Angle
21                             16. Other
22                           1. Rear End
23              

In [124]:
try:
    from sklearn.preprocessing import OrdinalEncoder # just to raise an ImportError if Scikit-Learn < 0.20
    from sklearn.preprocessing import OneHotEncoder
except ImportError:
    from future_encoders import OneHotEncoder # Scikit-Learn < 0.20

coll_encoder = OneHotEncoder()
coll_cat_1hot = coll_encoder.fit_transform(coll_cat)
print(coll_cat_1hot)

light_encoder = OneHotEncoder()
light_cat_1hot = light_encoder.fit_transform(light_cat)
print(light_cat_1hot)

roadway_encoder = OneHotEncoder()
roadway_cat_1hot = roadway_encoder.fit_transform(roadway_cat)
print(roadway_cat_1hot)


weather_encoder = OneHotEncoder()
weather_cat_1hot = weather_encoder.fit_transform(weather_cat)
print(weather_cat_1hot)

  (0, 0)	1.0
  (1, 7)	1.0
  (2, 14)	1.0
  (3, 14)	1.0
  (4, 0)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 7)	1.0
  (8, 1)	1.0
  (9, 14)	1.0
  (10, 14)	1.0
  (11, 7)	1.0
  (12, 0)	1.0
  (13, 8)	1.0
  (14, 7)	1.0
  (15, 9)	1.0
  (16, 0)	1.0
  (17, 7)	1.0
  (18, 7)	1.0
  (19, 0)	1.0
  (20, 7)	1.0
  (21, 6)	1.0
  (22, 0)	1.0
  (23, 3)	1.0
  (24, 0)	1.0
  :	:
  (10014, 14)	1.0
  (10015, 6)	1.0
  (10016, 10)	1.0
  (10017, 0)	1.0
  (10018, 0)	1.0
  (10019, 0)	1.0
  (10020, 0)	1.0
  (10021, 0)	1.0
  (10022, 7)	1.0
  (10023, 7)	1.0
  (10024, 0)	1.0
  (10025, 7)	1.0
  (10026, 0)	1.0
  (10027, 14)	1.0
  (10028, 9)	1.0
  (10029, 0)	1.0
  (10030, 7)	1.0
  (10031, 7)	1.0
  (10032, 0)	1.0
  (10033, 10)	1.0
  (10034, 7)	1.0
  (10035, 14)	1.0
  (10036, 2)	1.0
  (10037, 6)	1.0
  (10038, 0)	1.0
  (0, 4)	1.0
  (1, 3)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (5, 1)	1.0
  (6, 1)	1.0
  (7, 1)	1.0
  (8, 1)	1.0
  (9, 1)	1.0
  (10, 3)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 0)	1.0
  (14, 1)	1.0
  (15, 1)	1.0
  (16,

In [126]:
coll_array = coll_cat_1hot.toarray()
coll_array

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [127]:
light_array = light_cat_1hot.toarray()
light_array

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [128]:
roadway_array = roadway_cat_1hot.toarray()
roadway_array

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [129]:
weather_array = weather_cat_1hot.toarray()
weather_array

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [130]:
import numpy as np 

new_matrix= np.hstack((coll_array, light_array, roadway_array, weather_array))
new_matrix

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [133]:
from sklearn.linear_model import LinearRegression

injury = crash2['injury']
print(injury)
lin_reg = LinearRegression()
#lin_reg.fit(new_matrix,insurance_labels)


0        0
1        1
2        1
3        0
4        0
5        0
6        0
7        1
8        0
9        0
10       0
11       0
12       1
13       0
14       0
15       0
16       0
17       0
18       1
19       0
20       0
21       0
22       0
23       1
24       0
25       0
26       0
27       0
28       1
29       0
        ..
10009    1
10010    0
10011    1
10012    1
10013    1
10014    1
10015    1
10016    1
10017    0
10018    0
10019    0
10020    0
10021    0
10022    0
10023    0
10024    1
10025    1
10026    0
10027    0
10028    1
10029    0
10030    0
10031    1
10032    0
10033    0
10034    1
10035    0
10036    0
10037    0
10038    1
Name: injury, Length: 10039, dtype: int64
